server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.18.131
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.18.131
ly: #首先把一些常量抽取到application.yml
  sms:
    accessKeyId: 88888 # 自己的accessKeyId
    accessKeySecret: 8888888 # 自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: **** # 模板名称,ID密码请去阿里云官方申请
